services:

  kengrok:
    container_name: kengrok
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kengrok-network

  nginx:
    container_name: kengrok-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kengrok
    networks:
      - kengrok-network

  redis:
    container_name: kengrok-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - kengrok-network
    volumes:
      - redis-data:/data

networks:
  kengrok-network:
    driver: bridge

volumes:
  redis-data:
