services:

  kengrok:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kengrok
    networks:
      - kengrok-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - kengrok-network
    volumes:
      - redis-data:/data

networks:
  kengrok-network:
    driver: bridge

volumes:
  redis-data:
