// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: proto/proxy-manager.proto

package proxy_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndProxyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subdomain string `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
}

func (x *EndProxyRequest) Reset() {
	*x = EndProxyRequest{}
	mi := &file_proto_proxy_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndProxyRequest) ProtoMessage() {}

func (x *EndProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndProxyRequest.ProtoReflect.Descriptor instead.
func (*EndProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_manager_proto_rawDescGZIP(), []int{0}
}

func (x *EndProxyRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

type StartProxyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subdomain string `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Port      int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *StartProxyRequest) Reset() {
	*x = StartProxyRequest{}
	mi := &file_proto_proxy_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProxyRequest) ProtoMessage() {}

func (x *StartProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProxyRequest.ProtoReflect.Descriptor instead.
func (*StartProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_manager_proto_rawDescGZIP(), []int{1}
}

func (x *StartProxyRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *StartProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type StartProxyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *StartProxyResponse) Reset() {
	*x = StartProxyResponse{}
	mi := &file_proto_proxy_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProxyResponse) ProtoMessage() {}

func (x *StartProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProxyResponse.ProtoReflect.Descriptor instead.
func (*StartProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_proxy_manager_proto_rawDescGZIP(), []int{2}
}

func (x *StartProxyResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_proto_proxy_manager_proto protoreflect.FileDescriptor

var file_proto_proxy_manager_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2d, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75,
	0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x75, 0x62, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x28, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x32, 0xa9, 0x01, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x53, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x64, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proxy_manager_proto_rawDescOnce sync.Once
	file_proto_proxy_manager_proto_rawDescData = file_proto_proxy_manager_proto_rawDesc
)

func file_proto_proxy_manager_proto_rawDescGZIP() []byte {
	file_proto_proxy_manager_proto_rawDescOnce.Do(func() {
		file_proto_proxy_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proxy_manager_proto_rawDescData)
	})
	return file_proto_proxy_manager_proto_rawDescData
}

var file_proto_proxy_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_proxy_manager_proto_goTypes = []any{
	(*EndProxyRequest)(nil),    // 0: proxy_manager.EndProxyRequest
	(*StartProxyRequest)(nil),  // 1: proxy_manager.StartProxyRequest
	(*StartProxyResponse)(nil), // 2: proxy_manager.StartProxyResponse
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_proto_proxy_manager_proto_depIdxs = []int32{
	1, // 0: proxy_manager.ProxyManager.StartProxy:input_type -> proxy_manager.StartProxyRequest
	0, // 1: proxy_manager.ProxyManager.EndProxy:input_type -> proxy_manager.EndProxyRequest
	2, // 2: proxy_manager.ProxyManager.StartProxy:output_type -> proxy_manager.StartProxyResponse
	3, // 3: proxy_manager.ProxyManager.EndProxy:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proxy_manager_proto_init() }
func file_proto_proxy_manager_proto_init() {
	if File_proto_proxy_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proxy_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proxy_manager_proto_goTypes,
		DependencyIndexes: file_proto_proxy_manager_proto_depIdxs,
		MessageInfos:      file_proto_proxy_manager_proto_msgTypes,
	}.Build()
	File_proto_proxy_manager_proto = out.File
	file_proto_proxy_manager_proto_rawDesc = nil
	file_proto_proxy_manager_proto_goTypes = nil
	file_proto_proxy_manager_proto_depIdxs = nil
}
